<?xml version="1.0"?>

<robot name="skidbot" xmlns:xacro="http://www.ros.org/wiki/xacro">

<!-- ****************************************************** skidbot Robot *************************************************************  -->
<!-- Muthanna Alwahash                                                                                                                  -->
<!-- March 2022                                                                                                                         -->
<!-- *********************************************************************************************************************************  -->

<!-- ****************************************************** Base *********************************************************************  -->

  <gazebo reference="base">
    <material>Gazebo/Blue</material>
  </gazebo>

<!-- ******************************************************  Joint States Publisher **************************************************  -->

  <gazebo>
    <plugin name="joint_states_pub" filename="libgazebo_ros_joint_state_publisher.so">
      <ros>
        <namespace>${name_space}</namespace>
      </ros>
      <joint_name>front_left_wheel_joint</joint_name>
      <joint_name>back_left_wheel_joint</joint_name>
      <joint_name>front_right_wheel_joint</joint_name>
      <joint_name>back_right_wheel_joint</joint_name>
      <update_rate>100.0</update_rate>
    </plugin>
 </gazebo>

<!-- ******************************************************  Skid Steer Drive Controller *********************************************  -->

  <gazebo>
    <plugin name="skid_drive" filename="libgazebo_ros_diff_drive.so">
      <ros>
        <namespace>${name_space}</namespace>        
      </ros>
      <num_wheel_pairs>2</num_wheel_pairs>
      <!-- 1st Wheels Set -->
      <left_joint>front_left_wheel_joint</left_joint>
      <right_joint>front_right_wheel_joint</right_joint>
      <wheel_separation>${wheel_y*2}</wheel_separation>
      <wheel_diameter>${wheel_radius*2}</wheel_diameter>
      <!-- 2nd Wheels Set -->
      <left_joint>back_left_wheel_joint</left_joint>
      <right_joint>back_right_wheel_joint</right_joint>
      <wheel_separation>${wheel_y*2}</wheel_separation>
      <wheel_diameter>${wheel_radius*2}</wheel_diameter>
      <max_wheel_torque>20</max_wheel_torque>
      <max_wheel_acceleration>1.0</max_wheel_acceleration>
      <update_rate>100.0</update_rate>
      <robot_base_frame>footprint</robot_base_frame>
      <odometry_frame>odom</odometry_frame>
      <publish_odom>true</publish_odom>
      <publish_odom_tf>true</publish_odom_tf>
      <publish_wheel_tf>true</publish_wheel_tf>
    </plugin>
  </gazebo>

<!-- ******************************************************  Camera ******************************************************************  -->

  <gazebo reference="camera">
    <sensor type="camera" name="camera_sensor">
      <plugin name="camera" filename="libgazebo_ros_camera.so">
        <ros>
          <namespace>${name_space}</namespace>
        </ros>
        <camera_name>camera</camera_name>
        <frame_name>camera</frame_name>
        <hack_baseline>0.07</hack_baseline>
      </plugin>
      <update_rate>30.0</update_rate>
      <always_on>1</always_on>
      <camera name="camera">
        <horizontal_fov>${radians(80)}</horizontal_fov>
        <image>
          <width>1280</width>
          <height>720</height>
          <format>R8G8B8</format>
        </image>
        <clip>
          <near>0.02</near>
          <far>300</far>
        </clip>
        <distortion>
          <k1>0.0</k1>
          <k2>0.0</k2>
          <k3>0.0</k3>
          <p1>0.0</p1>
          <p2>0.0</p2>
          <center>0.5 0.5</center>
        </distortion>
      </camera>
    </sensor>
    <material>Gazebo/Green</material>
  </gazebo>

<!-- ****************************************************** hokuyo  ******************************************************************  -->

  <gazebo reference="hokuyo">
    <sensor type="ray" name="head_hokuyo_sensor">
      <plugin name="hokuyo" filename="libgazebo_ros_ray_sensor.so">
        <ros>
          <namespace>${name_space}</namespace>
        </ros>
        <output_type>sensor_msgs/LaserScan</output_type>
      </plugin>
      <update_rate>30</update_rate>
      <pose>0 0 0 0 0 0</pose>
      <visualize>false</visualize>
      <ray>
        <scan>
          <horizontal>
            <samples>720</samples>
            <resolution>1</resolution>
            <min_angle>-${radians(90)}</min_angle>
            <max_angle> ${radians(90)}</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.10</min>
          <max>30.0</max>
          <resolution>0.01</resolution>
        </range>
<!-- Noise parameters based on published spec for Hokuyo laser achieving "+-30mm" accuracy at range < 10m.  A mean of 0.0m and stddev   -->
<!-- of 0.01m will put 99.7% of samples within 0.03m of the true reading.                                                               -->
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>0.01</stddev>
        </noise>
      </ray>
    </sensor>
    <!-- <material>Gazebo/Red</material> -->
  </gazebo>

<!-- ****************************************************** end **********************************************************************  -->

</robot>