<?xml version='1.0'?>

<robot name="bocbot" xmlns:xacro="http://www.ros.org/wiki/xacro">

<!-- ****************************************************** bocbot Robot *************************************************************  -->
<!-- Muthanna Alwahash                                                                                                                  -->
<!-- March 2022                                                                                                                         -->
<!-- *********************************************************************************************************************************  -->

<!-- ****************************************************** Parameters ***************************************************************  --> 
 
  <xacro:property name="mesh_path"      value="package://robot_gazebo/meshes/bocbot/"/>

  <xacro:property name="base_mass"      value="15.0"                              /> <!-- arbitrary mass value                          -->
  <xacro:property name="base_width"     value="0.20"                              />
  <xacro:property name="base_length"    value="0.40"                              />
  <xacro:property name="base_height"    value="0.10"                              />
  
  <xacro:property name="wheel_mass"     value="5.0"                               /> 
  <xacro:property name="wheel_width"    value="0.05"                              />
  <xacro:property name="wheel_radius"   value="0.10"                              />

  <xacro:property name="camera_mass"    value="0.1"                               /> 
  <xacro:property name="camera_width"   value="0.05"                              />
  <xacro:property name="camera_length"  value="0.05"                              />
  <xacro:property name="camera_height"  value="0.05"                              />

  <xacro:property name="hokuyo_mass"    value="1e-5"                              />
  <xacro:property name="hokuyo_width"   value="0.05"                              />
  <xacro:property name="hokuyo_length"  value="0.05"                              />
  <xacro:property name="hokuyo_height"  value="0.080165"                          />

  <xacro:property name="y_offset"       value="${(base_width+wheel_width*1.2)/2}" />
  <xacro:property name="z_offset"       value="${base_height/2}"                  /> 

<!-- ****************************************************** Includes *****************************************************************  --> 

  <xacro:include filename="$(find robot_gazebo)/xacro/common_rviz_materials.xacro" />   <!-- RVIZ Colors                                -->
  <xacro:include filename="$(find robot_gazebo)/gazebo/gz_bocbot.xacro" />              <!-- Gazebo                                     -->

<!-- ****************************************************** Base Footprint ***********************************************************  -->

  <link name="footprint"></link>

<!-- ****************************************************** Base *********************************************************************  -->

  <link name='base'>
    <pose>0 0 0.1 0 0 0</pose>
    <inertial>
      <mass value="${base_mass}"/>
      <origin xyz="0 0 0" rpy=" 0 0 0"/>
      <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1" />
    </inertial>
    <collision name='collision'>
      <origin xyz="0 0 0" rpy=" 0 0 0"/>
      <geometry>
        <mesh filename="${mesh_path}base.stl" scale="1 1 1"/>  <!--  <box size="${base_length} ${base_width} ${base_height}"/> -->
      </geometry>
    </collision>
    <visual name='base_visual'>
      <origin xyz="0 0 0" rpy=" 0 0 0"/>
      <geometry>
        <mesh filename="${mesh_path}base.stl" scale="1 1 1"/>  <!--  <box size="${base_length} ${base_width} ${base_height}"/> -->
      </geometry>
      <material name="blue"/>
    </visual>
  </link>

<!-- ****************************************************** Front Left Wheel *********************************************************  -->

  <link name="front_left_wheel">
    <inertial>
      <mass value="${base_mass}"/>
      <origin xyz="0 0 0" rpy=" 0 ${radians(90)} ${radians(90)}"/>
      <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1" />
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy=" 0 ${radians(90)} ${radians(90)}"/>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
      <material name="grey"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy=" 0 ${radians(90)} ${radians(90)}"/>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
    </collision>
  </link>

<!-- ****************************************************** Back Left Wheel **********************************************************  -->

  <link name="back_left_wheel">
    <inertial>
      <mass value="${base_mass}"/>
      <origin xyz="0 0 0" rpy=" 0 ${radians(90)} ${radians(90)}"/>
      <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1" />
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy=" 0 ${radians(90)} ${radians(90)}"/>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
      <material name="grey"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy=" 0 ${radians(90)} ${radians(90)}"/>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
    </collision>
  </link>

<!-- ****************************************************** Front Right Wheel ********************************************************  -->

  <link name="front_right_wheel">
    <inertial>
      <mass value="${base_mass}"/>
      <origin xyz="0 0 0" rpy=" 0 ${radians(90)} ${radians(90)}"/>
      <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1" />
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy=" 0 ${radians(90)} ${radians(90)}"/>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
      <material name="grey"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy=" 0 ${radians(90)} ${radians(90)}"/>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
    </collision>
  </link>

<!-- ****************************************************** Back Right Wheel *********************************************************  -->

  <link name="back_right_wheel">
    <inertial>
      <mass value="${base_mass}"/>
      <origin xyz="0 0 0" rpy=" 0 ${radians(90)} ${radians(90)}"/>
      <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1" />
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy=" 0 ${radians(90)} ${radians(90)}"/>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
      <material name="grey"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy=" 0 ${radians(90)} ${radians(90)}"/>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
    </collision>
  </link>

<!-- ****************************************************** Camera *******************************************************************  -->

  <link name="camera">
    <inertial>
      <mass value="${camera_mass}"/>
      <origin xyz="0 0 0" rpy=" 0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
    <visual name="camera_visual">
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="${camera_length} ${camera_width} ${camera_height}"/>
      </geometry>
      <material name="green"/>
    </visual>
    <collision name="camera_colision">
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="${camera_length} ${camera_width} ${camera_height}"/>
      </geometry>
    </collision>
  </link>

<!-- ****************************************************** Hokuyo *******************************************************************  -->

  <link name="hokuyo">
    <inertial>
      <mass value="${hokuyo_mass}"/>
      <origin xyz="0 0 0" rpy=" 0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
    <visual name="hokuyo_visual">
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="${mesh_path}hokuyo.dae"/> <!--  <box size="${hokuyo_length} ${hokuyo_width} ${hokuyo_height}"/> -->
      </geometry>
      <material name="red"/>
    </visual>
    <collision name="hokuyo_colision">
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="${mesh_path}hokuyo.dae"/> <!--  <box size="${hokuyo_length} ${hokuyo_width} ${hokuyo_height}"/> -->
      </geometry>
    </collision>
  </link>

<!-- ****************************************************** Footprint Joint **********************************************************  -->

  <joint type="fixed" name="footprint_joint" >
    <origin xyz="0 0 0" rpy="0 0 0" />
    <parent link="footprint"/>
    <child link="base" />
  </joint>

<!-- ****************************************************** Front Left Wheel Joint ***************************************************  -->

  <joint type="continuous" name="front_left_wheel_joint">
    <origin xyz="0.12 0.15 0" rpy="0 0 0"/>
    <child link="front_left_wheel"/>
    <parent link="base"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
    <limit effort="10000" velocity="1000"/>
    <dynamics damping="1.0" friction="1.0"/>
  </joint>

<!-- ****************************************************** Front Right Wheel Joint **************************************************  -->

  <joint type="continuous" name="front_right_wheel_joint">
    <origin xyz="0.12 -0.15 0" rpy="0 0 0"/>
    <child link="front_right_wheel"/>
    <parent link="base"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
    <limit effort="10000" velocity="1000"/>
    <dynamics damping="1.0" friction="1.0"/>
  </joint>

<!-- ****************************************************** Back Left Wheel Joint ****************************************************  -->

  <joint type="continuous" name="back_left_wheel_joint">
    <origin xyz="-0.12 0.15 0" rpy="0 0 0"/>
    <child link="back_left_wheel"/>
    <parent link="base"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
    <limit effort="10000" velocity="1000"/>
    <dynamics damping="1.0" friction="1.0"/>
  </joint>

<!-- ****************************************************** Back Right Wheel Joint ***************************************************  -->

  <joint type="continuous" name="back_right_wheel_joint">
    <origin xyz="-0.12 -0.15 0" rpy="0 0 0"/>
    <child link="back_right_wheel"/>
    <parent link="base"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
    <limit effort="10000" velocity="1000"/>
    <dynamics damping="1.0" friction="1.0"/>
  </joint>

<!-- ****************************************************** Camera Joint *************************************************************  -->

  <joint type="fixed" name="camera_joint">
    <origin xyz="0.2 0 0" rpy="0 0 0"/>
    <child link="camera"/>
    <parent link="base"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
  </joint>

<!-- ****************************************************** Hokuyo Joint *************************************************************  -->

  <joint type="fixed" name="hokuyo_joint">
    <origin xyz="0.15 0 0.1" rpy="0 0 0"/>
    <child link="hokuyo"/>
    <parent link="base"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
  </joint>

<!-- ****************************************************** end **********************************************************************  -->

</robot>