<?xml version="1.0"?>
<robot name="diffbot" xmlns:xacro="http://www.ros.org/wiki/xacro">

<!-- ****************************************************** diffbot Robot ************************************************************  -->
<!-- Muthanna Alwahash                                                                                                                  -->
<!-- March 2022                                                                                                                         -->
<!-- *********************************************************************************************************************************  -->

<!-- ****************************************************** Parameters ***************************************************************  --> 
 
  <xacro:property name="base_mass"            value="0.3"               /> <!-- arbitrary value for base mass             -->
  <xacro:property name="base_width"           value="0.10"              />
  <xacro:property name="base_length"          value="0.20"              />
  <xacro:property name="base_height"          value="0.05"              />
  <xacro:property name="wheel_mass"           value="0.3"               /> <!-- arbitrary value for wheel mass            -->
  <xacro:property name="wheel_width"          value="0.010"             />
  <xacro:property name="wheel_radius"         value="0.025"             />
  <xacro:property name="caster_wheel_mass"    value="0.1"               /> <!-- arbitrary value for caster wheel mass     -->
  <xacro:property name="caster_wheel_radius"  value="${wheel_radius}"   />
  <xacro:property name="z_offset"             value="-${base_height/2}" /> <!-- Space btw top of beam and the each joint  -->
    
<!-- ****************************************************** Includes *****************************************************************  --> 

  <xacro:include filename="$(find robot_gazebo)/xacro/common_rviz_materials.xacro" />   <!-- RVIZ Colors                                -->
  <xacro:include filename="$(find robot_gazebo)/gazebo/gz_diffbot.xacro" />             <!-- Gazebo                                     -->

<!-- ****************************************************** Macro ********************************************************************  --> 

  <xacro:macro name="diffbot" params="prefix">

<!-- ****************************************************** Base Footprint ***********************************************************  -->

    <link name="${prefix}base_footprint"/>

<!-- ****************************************************** Base Joint ***************************************************************  -->

    <joint name="base_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="${prefix}base_link"/>
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
    </joint>

<!-- ****************************************************** Base Link ****************************************************************  -->

  <link name="${prefix}base_link">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${base_width} ${base_length} ${base_height}"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <material name="orange"/>
    </visual>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${base_mass}"/>
      <inertia
        ixx="${base_mass / 12.0 * (base_length*base_length + base_height*base_height)}" ixy="0.0" ixz="0.0"
        iyy="${base_mass / 12.0 * (base_height*base_height + base_width*base_width)}" iyz="0.0"
        izz="${base_mass / 12.0 * (base_width*base_width + base_length*base_length)}"/>
    </inertial>
  </link>

<!-- ****************************************************** Left Wheel Joint *********************************************************  -->

    <joint name="${prefix}left_wheel_joint" type="continuous">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}left_wheel"/>
      <origin xyz="0 -${(base_width+wheel_width)/2} ${z_offset}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <dynamics damping="0.2"/>
    </joint>

<!-- ****************************************************** Left Wheel Link **********************************************************  -->

    <link name="${prefix}left_wheel">
      <collision>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
        </geometry>
      </collision>
      <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
        </geometry>
        <material name="black"/>
      </visual>
      <inertial>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <mass value="${wheel_mass}"/>
        <inertia
          ixx="${wheel_mass / 12.0 * (3*wheel_radius + wheel_width*wheel_width)}" ixy="0.0" ixz="0.0"
          iyy="${wheel_mass / 12.0 * wheel_radius*wheel_radius}" iyz="0.0"
          izz="${wheel_mass / 12.0 * wheel_radius*wheel_radius}"/>
      </inertial>
    </link>

<!-- ****************************************************** Right Wheel Joint ********************************************************  -->

    <joint name="${prefix}right_wheel_joint" type="continuous">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}right_wheel"/>
      <origin xyz="0 ${(base_width+wheel_width)/2} ${z_offset}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <dynamics damping="0.2"/>
    </joint>

<!-- ****************************************************** Right Wheel Link ********************************************************  -->

    <link name="${prefix}right_wheel">
      <collision>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
        </geometry>
      </collision>
      <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
        </geometry>
        <material name="black"/>
      </visual>
      <inertial>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <mass value="${wheel_mass}"/>
        <inertia
          ixx="${wheel_mass / 12.0 * (3*wheel_radius + wheel_width*wheel_width)}" ixy="0.0" ixz="0.0"
          iyy="${wheel_mass / 12.0 * wheel_radius*wheel_radius}" iyz="0.0"
          izz="${wheel_mass / 12.0 * wheel_radius*wheel_radius}"/>
      </inertial>
    </link>

<!-- ****************************************************** Front caster joint *******************************************************  -->

    <joint name="${prefix}front_caster_joint" type="fixed">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}front_caster"/>
      <origin xyz="${base_length/2 - caster_wheel_radius} 0 ${z_offset}" rpy="0 0 0"/>
    </joint>

<!-- ****************************************************** Front caster Link ********************************************************  -->

    <link name="${prefix}front_caster">
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${caster_wheel_radius}"/>
        </geometry>
      </collision>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${caster_wheel_radius}"/>
        </geometry>
        <material name="white"/>
      </visual>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${caster_wheel_mass}"/>
        <inertia
          ixx="${caster_wheel_mass * 0.4 * (caster_wheel_radius * caster_wheel_radius)}" ixy="0.0" ixz="0.0"
          iyy="${caster_wheel_mass * 0.4 * (caster_wheel_radius * caster_wheel_radius)}" iyz="0.0"
          izz="${caster_wheel_mass * 0.4 * (caster_wheel_radius * caster_wheel_radius)}"/>
      </inertial>
    </link>

<!-- ****************************************************** Rear Caster Joint ********************************************************  -->

    <joint name="${prefix}rear_caster_joint" type="fixed">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}rear_caster"/>
      <origin xyz="${-base_length/2 + caster_wheel_radius} 0 ${z_offset}" rpy="0 0 0"/>
    </joint>

<!-- ****************************************************** Rear Caster Link *********************************************************  -->

    <link name="${prefix}rear_caster">
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${caster_wheel_radius}"/>
        </geometry>
      </collision>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${caster_wheel_radius}"/>
        </geometry>
        <material name="white"/>
      </visual>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${caster_wheel_mass}"/>
        <inertia
          ixx="${caster_wheel_mass * 0.4 * (caster_wheel_radius * caster_wheel_radius)}" ixy="0.0" ixz="0.0"
          iyy="${caster_wheel_mass * 0.4 * (caster_wheel_radius * caster_wheel_radius)}" iyz="0.0"
          izz="${caster_wheel_mass * 0.4 * (caster_wheel_radius * caster_wheel_radius)}"/>
      </inertial>
    </link>

<!-- ****************************************************** End Macro ****************************************************************  -->

  </xacro:macro>

<!-- ****************************************************** Expand Macro *************************************************************  -->
  
  <xacro:diffbot prefix="" />
   
<!-- ****************************************************** END **********************************************************************  -->

</robot>
