<?xml version="1.0" encoding="UTF-8" ?>

<robot name="razbot" xmlns:xacro="http://ros.org/wiki/xacro">

<!-- ****************************************************** Razbot Robot *************************************************************  -->
<!-- Muthanna Alwahash                                                                                                                  -->
<!-- March 2022                                                                                                                         -->
<!-- Originally developed by Shubhankar Das a.k.a Razbotics                                                                             -->
<!-- *********************************************************************************************************************************  -->

<!-- ****************************************************** Parameters ***************************************************************  -->

	<xacro:property name="body_length_x"        value="0.294" />
	<xacro:property name="body_length_y"        value="0.340" />
	<xacro:property name="coxa_length"          value="0.052" />
	<xacro:property name="femur_length"         value="0.065" />
	<xacro:property name="tibia_length"         value="0.133" />

	<xacro:property name="joint_lower_limit"    value="-${3.14}" />
	<xacro:property name="joint_upper_limit"    value="${3.14}" />
	<xacro:property name="joint_effort"         value="6.0" />
	<xacro:property name="joint_velocity"       value="0.524" />

<!-- ****************************************************** Colors *******************************************************************  -->

    <material name="red">
        <color rgba="1.0 0.0 0.0 1.0"/>
    </material>

    <material name="green">
        <color rgba="0.0 1.0 0.0 1.0"/>
    </material>

    <material name="blue">
        <color rgba="0.0 0.0 1.0 1.0"/>
    </material>

    <material name="black">
        <color rgba="0.3 0.3 0.3 1.0"/>
    </material>

    <material name="white">
        <color rgba="1.0 1.0 1.0 1.0"/>
    </material>

<!-- ******************************************************  *************************************************************************  -->

    <link name="base_link"/>

<!-- ******************************************************  *************************************************************************  -->

    <joint name="base_joint" type="fixed">
        <parent link="base_link" />
        <child link="body_link" />
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
    </joint>

<!-- ******************************************************  *************************************************************************  -->
	<link name="body_link">
        <visual>
            <origin	xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
            <geometry>
                <mesh filename="package://robot_gazebo/meshes/razbot/body.stl" scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="blue"/>
        </visual>

        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <mesh filename="package://robot_gazebo/meshes/razbot/body.stl" scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="blue"/>
        </collision>

        <inertial>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
            <mass value="0.00001"/>
            <inertia
                ixx="1.0" ixy="0.0"  ixz="0.0"
                iyy="1.0" iyz="0.0"
                izz="1.0" />
        </inertial>
    </link>

<!-- ******************************************************  *************************************************************************  -->

	<!-- IMU properties -->
	<joint name="imu_joint" type="fixed">
		<parent link="base_link" />
		<child link="imu_link" />
		<origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
	</joint>

<!-- ******************************************************  *************************************************************************  -->

	<link name="imu_link">
        <inertial>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
            <mass value="0.00001"/>
            <inertia
                ixx="1.0" ixy="0.0"  ixz="0.0"
                iyy="1.0" iyz="0.0"
                izz="1.0" />
        </inertial>
    </link>

<!-- ******************************************************  *************************************************************************  -->
	<!-- Leg macro -->
	<xacro:macro name="leg" params="side position x y angle axis">
<!-- ******************************************************  *************************************************************************  -->
		<!-- leg position -->
		<joint name="leg_center_joint_${side}${position}" type="fixed">
			<origin xyz="${x} ${y} 0.0" rpy="0.0 0.0 0.0" />
			<parent link="body_link" />
			<child link="leg_center_${side}${position}" />
		</joint>
<!-- ******************************************************  *************************************************************************  -->
		<link name="leg_center_${side}${position}" >
            <inertial>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
                <mass value="0.00001"/>
                <inertia
                    ixx="1.0" ixy="0.0"  ixz="0.0"
                    iyy="1.0" iyz="0.0"
                    izz="1.0" />
            </inertial>
        </link>
<!-- ******************************************************  *************************************************************************  -->
		<!-- coxa -->
		<joint name="coxa_joint_${side}${position}" type="revolute">
			<origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 ${angle}" />
			<parent link="leg_center_${side}${position}" />
			<child link="coxa_${side}${position}" />
			<axis xyz="0.0 0.0 1.0" />
			<limit lower="${joint_lower_limit}" upper="${joint_upper_limit}" effort="${joint_effort}" velocity="${joint_velocity}" />
		</joint>
<!-- ******************************************************  *************************************************************************  -->
		<transmission name="coxa_transmission_${side}${position}">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="coxa_joint_${side}${position}">
                <hardwareInterface>EffortJointInterface</hardwareInterface>
            </joint>
            <actuator name="coxa_motor_${side}${position}">
                <hardwareInterface>EffortJointInterface</hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission>
<!-- ******************************************************  *************************************************************************  -->
        <link name="coxa_${side}${position}">

            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <mesh filename="package://robot_gazebo/meshes/razbot/coxa.stl" scale="0.001 0.001 0.001"/>
                </geometry>
                <material name="green"/>
            </visual>

            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
                <geometry>
                    <mesh filename="package://robot_gazebo/meshes/razbot/coxa.stl" scale="0.001 0.001 0.001"/>
                </geometry>
                <material name="green"/>
            </collision>

            <inertial>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
                <mass value="0.00001"/>
                <inertia
                    ixx="1.0" ixy="0.0"  ixz="0.0"
                    iyy="1.0" iyz="0.0"
                    izz="1.0" />
            </inertial>

        </link>

<!-- ******************************************************  *************************************************************************  -->
		<!-- femur -->
		<joint name="femur_joint_${side}${position}" type="revolute">
			<origin xyz="${coxa_length} 0.0 0.0" rpy="-${pi/2} ${pi/2} 0.0" />
			<parent link="coxa_${side}${position}" />
			<child link="femur_${side}${position}" />
			<axis xyz="0.0 0.0 ${-axis}" />
			<limit lower="${joint_lower_limit}" upper="${joint_upper_limit}" effort="${joint_effort}" velocity="${joint_velocity}" />
		</joint>
<!-- ******************************************************  *************************************************************************  -->
		<transmission name="femur_transmission_${side}${position}">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="femur_joint_${side}${position}">
                <hardwareInterface>EffortJointInterface</hardwareInterface>
            </joint>
            <actuator name="femur_motor_${side}${position}">
                <hardwareInterface>EffortJointInterface</hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission>
<!-- ******************************************************  *************************************************************************  -->
        <link name="femur_${side}${position}">
            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <mesh filename="package://robot_gazebo/meshes/razbot/femur.stl" scale="0.001 0.001 0.001"/>
                </geometry>
                <material name="red"/>
            </visual>
            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
                <geometry>
                    <mesh filename="package://robot_gazebo/meshes/razbot/femur.stl" scale="0.001 0.001 0.001"/>
                </geometry>
                <material name="red"/>
            </collision>
            <inertial>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
                <mass value="0.00001"/>
                <inertia
                    ixx="1.0" ixy="0.0"  ixz="0.0"
                    iyy="1.0" iyz="0.0"
                    izz="1.0" />
            </inertial>
        </link>

<!-- ******************************************************  *************************************************************************  -->
		<!-- tibia -->
		<joint name="tibia_joint_${side}${position}" type="revolute">
			<origin xyz="0.0 -${femur_length} 0.0" rpy="${pi} 0.0 0.0" />
			<parent link="femur_${side}${position}" />
			<child link="tibia_${side}${position}" />
			<axis xyz="0.0 0.0 ${axis}" />
			<limit lower="${joint_lower_limit}" upper="${joint_upper_limit}" effort="${joint_effort}" velocity="${joint_velocity}" />
		</joint>
<!-- ******************************************************  *************************************************************************  -->
		<transmission name="tibia_transmission_${side}${position}">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="tibia_joint_${side}${position}">
                <hardwareInterface>EffortJointInterface</hardwareInterface>
            </joint>
            <actuator name="tibia_motor_${side}${position}">
                <hardwareInterface>EffortJointInterface</hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission>
<!-- ******************************************************  *************************************************************************  -->
        <link name="tibia_${side}${position}">
            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <mesh filename="package://robot_gazebo/meshes/razbot/tibia.stl" scale="0.001 0.001 0.001"/>
                </geometry>
                <material name="green"/>
            </visual>
            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
                <geometry>
                    <mesh filename="package://robot_gazebo/meshes/razbot/tibia.stl" scale="0.001 0.001 0.001"/>
                </geometry>
                <material name="green"/>
            </collision>
            <inertial>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
                <mass value="0.00001"/>
                <inertia
                    ixx="1.0" ixy="0.0"  ixz="0.0"
                    iyy="1.0" iyz="0.0"
                    izz="1.0" />
            </inertial>
        </link>

<!-- ******************************************************  *************************************************************************  -->

	</xacro:macro>
    
<!-- ******************************************************  *************************************************************************  -->
<!-- Build robot model -->
	<xacro:leg side="R" position="R" x="-${body_length_x/2}" y="-${0.1695/2}" angle="-${5*pi/6}" axis="1" />
	<xacro:leg side="R" position="M" x="0.0" y="-${body_length_y/2}" angle="-${pi/2}" axis="1" />
	<xacro:leg side="R" position="F" x="${body_length_x/2}" y="-${0.1695/2}" angle="-${pi/6}" axis="1" />

	<xacro:leg side="L" position="R" x="-${body_length_x/2}" y="${0.1695/2}" angle="${5*pi/6}" axis="-1" />
	<xacro:leg side="L" position="M" x="0.0" y="${body_length_y/2}" angle="${pi/2}" axis="-1" />
	<xacro:leg side="L" position="F" x="${body_length_x/2}" y="${0.1695/2}" angle="${pi/6}" axis="-1" />
<!-- ******************************************************  *************************************************************************  -->
</robot>
